import streamlit as st
st.title("About the Project")
st.markdown("An overview of the architecture, methodology, and academic context of the Stock Prediction System.")
st.write("")
st.markdown("### 1. About the Application")
st.write("This application is an academic machine learning project designed to demonstrate a complete, end-to-end supervised learning workflow using historical stock market data. The project utilizes a Modular Monolithic Architecture built entirely in Python.")
st.write("")
st.markdown("### 2. Prediction Objective")
st.write("The primary objective is to predict the **Next Trading Day's Closing Price** and derive the expected market direction (UP/DOWN) based purely on historical technical data.")
st.write("")
st.markdown("### 3. Data Source & Feature Engineering")
st.write("- **Data Source**: Market data is retrieved dynamically from Yahoo Finance (`yfinance`).")
st.write("- **Features**: The system utilizes a simple, explainable feature set consisting of `Open`, `High`, `Low`, `Close`, `Volume`, and their respective 1-day lags.")
st.write("- **Data Integrity**: To strictly prevent future data leakage, the target variable (Next Day Close) is created by shifting the close price backwards. This ensures that a model predicting 'tomorrow' only ever has access to data from 'today' and before.")
st.write("")
st.markdown("### 4. Machine Learning Models")
st.write("The project evaluates exactly three regression models as per the academic requirements:")
st.write("- **Support Vector Regression (SVR)**")
st.write("- **Ridge Regression**")
st.write("- **HistGradientBoostingRegressor**")
st.write("")
st.markdown("### 5. Training, Evaluation, and Cross-Validation")
st.write("- **Chronological Split**: The dataset undergoes a strict chronological `70/30` Train/Test split. Random shuffling is strictly prohibited to respect the time-series nature of financial data.")
st.write("- **Metrics**: Models are evaluated on the test set using Root Mean Squared Error (`RMSE`), Residual Sum of Squares (`RSS`), and R-squared (`R²`).")
st.write("- **Validation**: The best-performing model on the test set is automatically selected and undergoes a rigorous **5-Fold TimeSeriesSplit** cross-validation to prove its stability across different historical timeframes.")
st.write("")
st.markdown("### 6. Currency Handling")
st.write("The application automatically detects the native currency of the selected stock. For foreign equities, it utilizes latest available foreign exchange rates to display secondary equivalent values in INR, offering localized context without altering the underlying native-currency ML predictions.")
st.write("")
st.markdown("### 7. Academic Context")
st.write("This project serves as a comprehensive demonstration of data engineering, machine learning pipelines, and interactive UI design, maintaining a strict adherence to syllabus guidelines and best practices in data science.")
