import streamlit as st

st.set_page_config(page_title="Disclaimer / Terms", page_icon="⚖️", layout="wide")

st.title("⚖️ Disclaimer & Terms of Use")

st.markdown("""
### 1. Educational and Academic Purpose Only
This application and its underlying machine learning models have been developed strictly for **educational and academic purposes**. The predictions, analysis, and expected directions generated by this system are outputs of academic regression algorithms and do not constitute professional financial advice.

### 2. Predictions are Estimates
The forecasted "Next Trading Day Close", "Predicted Change", and "Expected Direction" (UP/DOWN) are purely mathematical estimates based on historical market data. 

**Machine-learning predictions can be incorrect.** Financial markets are highly volatile and influenced by unpredictable real-world events, news, macroeconomic factors, and human sentiment that cannot be captured by historical OHLCV (Open, High, Low, Close, Volume) data alone.

### 3. No Guarantee of Future Performance
Past performance of a stock is not a reliable indicator of its future performance. The cross-validation metrics (RMSE, R²) shown in this application only reflect the model's performance on historical test data, not its guaranteed accuracy in live future markets.

### 4. Assumption of Risk
Any individual or entity attempting to use the outputs of this application for real-world trading or investment decisions does so entirely at their own risk. 

By using this application, you acknowledge that:
* The developers of this system bear **zero liability** for any financial losses or damages incurred.
* This system is not a substitute for your own research or consultation with a licensed financial advisor.
* Words like "Prediction", "Expected", and "Direction" reflect model output syntax, not a guaranteed "BUY", "SELL", or "PROFIT" signal.
""")
