import streamlit as st

st.title("Disclaimer & Terms of Use")
st.markdown("Important information regarding the limitations and intended use of the Stock Prediction System.")
st.write("")

with st.container(border=True):
    st.markdown("### 1. Educational and Academic Purpose Only")
    st.write("This application and its underlying machine learning models have been developed strictly for **educational and academic purposes**. The predictions, analysis, and expected directions generated by this system are outputs of academic regression algorithms and do not constitute professional financial advice.")

st.write("")
with st.container(border=True):
    st.markdown("### 2. Predictions are Estimates")
    st.write("The forecasted \"Next Trading Day Close\", \"Predicted Change\", and \"Expected Direction\" (UP/DOWN) are purely mathematical estimates based on historical market data.")
    st.write("**Machine-learning predictions can be incorrect.** Financial markets are highly volatile and influenced by unpredictable real-world events, news, macroeconomic factors, and human sentiment that cannot be fully captured by historical OHLCV (Open, High, Low, Close, Volume) data alone.")

st.write("")
with st.container(border=True):
    st.markdown("### 3. No Guarantee of Future Performance")
    st.write("Past performance of a stock is not a reliable indicator of its future performance. The cross-validation metrics (`RMSE`, `R²`) shown in this application only reflect the model's historical performance on isolated test data, not its guaranteed accuracy in live future markets.")

st.write("")
with st.container(border=True):
    st.markdown("### 4. Data Source and Currency Limitations")
    st.write("- **Data Delays**: Market data retrieved from Yahoo Finance may be subject to delays or inaccuracies. The system relies on the integrity of this third-party data.")
    st.write("- **FX Rates**: Currency conversions shown in the application utilize the latest available foreign exchange rates at the time of retrieval. These rates fluctuate constantly and the converted INR equivalents are approximate secondary indicators, not exact executable trading values.")

st.write("")
with st.container(border=True):
    st.markdown("### 5. Assumption of Risk")
    st.write("Any individual or entity attempting to use the outputs of this application for real-world trading or investment decisions does so entirely at their own risk.")
    st.write("By using this application, you acknowledge that:")
    st.write("- The developers of this system bear **zero liability** for any financial losses or damages incurred.")
    st.write("- This system is not a substitute for your own research or consultation with a licensed financial advisor.")
    st.write("- Words like \"Prediction\", \"Expected\", and \"Direction\" reflect model output syntax, not a guaranteed \"BUY\", \"SELL\", or \"PROFIT\" signal.")
